---
abstract: 'Simple OO style queue implementation.'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-Base
requires:
  Carp: 0
resources:
  bugtracker: http://github.com/russoz/Queue-Base/issues
  repository: git://github.com/russoz/Queue-Base.git
version: 2.201
